name: run pytest

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COVERAGE_SINGLE: 100
      COVERAGE_TOTAL: 100

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          python utils/downgrade_patch.py
          if [ -f requirements_test.txt ]; then pip install -r requirements_test.txt; fi

      - name: build coverage file
        run: |
          pytest --cache-clear --cov=dff tests/ > pytest-coverage.txt
      - name: comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
