name: run pytest

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          if [ -f requirements_test.txt ]; then pip install -r requirements_test.txt; fi

      - name: pytester-cov
        uses: alexanderdamiani/pytester-cov@v1.2.1
        with:
          # cov-omit-list: 'tests/*, examples/*, utils/*'
          cov-threshold-single: 100
          cov-threshold-total: 100